module.exports = {
  plugins: {
    // 'postcss-inline-comment'       : {},
    // 'postcss-strip-inline-comments': {},
    // 'postcss-simple-vars'          : {},
    // 'postcss-sassy-import'         : {},
    // 'postcss-sassy-mixins'         : {},
    // 'postcss-import': {},
    // 'postcss-nested'               : {},
    // 'postcss-for-var'              : {},
    // 'postcss-for'                  : {},
    // 'postcss-mixins'               : {},
    // 'postcss-sass-mixins'          : {},
    // 'postcss-include'              : {},
    'cssnano': {
      discardComments: {
        removeAll: true,
      },
      autoprefixer: false,
      discardDuplicates: true,
      discardOverridden: true,
      // mergeLonghand: true,
      // minifyFontValues: true,
      // minifyParams: true,
      // orderedValues: true,
      styleCache: false,
      discardEmpty: true,
      discardUnused: true,
      filterPlugins: true,
      mergeRules: true,
      // minifySelectors: true,
      // normalizeString: true,
      reduceIdents: false,
      reduceTransforms: false,
      zindex: false,
    },
    'postcss-preset-env': {
      stage: 0,
    },
  },
};
